import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { okfEnabled } from "./okf.js";

/** The managed block's fences (v1 – a future copy bump moves the version). */
export const AGENTS_BEGIN = "<!-- fragmt:begin v1 -->";
export const AGENTS_END = "<!-- fragmt:end -->";

/** The agent rules (M4-4 b5, approved copy; verify added in operator round
 *  4C): protected main, tool-owned sidecars, always --author, state and
 *  verification via `fragmt agent`. */
export const AGENTS_BODY = `## fragmt – docs environment for this repo
These docs are maintained through fragmt (git-native drafting).
Rules for agents:
- NEVER edit docs on main directly – main is protected. Run \`fragmt agent draft <doc>\` first; merge when done.
- NEVER hand-edit \`.docs/comments/*.json\` sidecars – use \`fragmt agent comment\`.
- ALWAYS pass \`--author "Your Name <you@example.invalid>"\` so your work is attributable.
- State check: \`fragmt agent status\`. Doc bodies are plain markdown – read them directly.
- Verify a reviewed doc with \`fragmt agent verify <doc> --as-actor "<producer>/<version>"\` – the actor is your self-declaration, never a false \`human:\`.
- New anchored comment threads are a UI act (they need a text selection); reply and resolve via the CLI.
`;

/**
 * The OKF-mode body (rungs 3–4): AGENTS_BODY verbatim with the OKF rules
 * section appended after it. The managed block is the only manual an agent
 * ever reads – an OKF bundle whose block stays silent about frontmatter,
 * reserved files, derived fields, actors, and `validate` is a bundle whose
 * rules cannot be followed, so the section ships in the same splice.
 */
export const AGENTS_BODY_OKF = `${AGENTS_BODY}## OKF rules – this repo is an OKF v0.2 bundle
- Every \`.md\` file needs frontmatter: a non-empty \`type\` and a \`status\` (\`draft\`/\`stable\`/\`deprecated\`). Additional keys are welcome and preserved byte-for-byte.
- \`index.md\` and \`log.md\` are reserved (no concept content). \`index.md\` is GENERATED by fragmt and regenerated whenever a folder's docs change – don't hand-write it.
- Body links are canonical. fragmt maintains \`references\`/\`referenced-by\` on every save – never hand-edit those fields.
- \`generated\` and \`verified\` are stamped by fragmt. Declare yourself with \`--as-actor "<producer>/<version>"\` (e.g. on \`fragmt agent verify\`); never write a \`human:\` actor yourself.
- New \`.md\` files you create should carry \`type: concept\` and \`status: "draft"\` frontmatter – or run \`fragmt validate --fix\` to add them mechanically.
- Before finishing work, run \`fragmt validate\` (exit 0 = conformant); \`--fix\` applies the mechanical repairs in one commit.
`;

/**
 * The outer repo's redirect block (#16): same fences as the standard block,
 * so re-running the nested-init (or a later copy bump) replaces in place.
 */
export function AGENTS_OUTER_BODY(folder: string): string {
	return `## fragmt – docs live in the nested repo at ${folder}/
Do NOT edit docs in this repo. \`cd ${folder}\` and follow the AGENTS.md there; fragmt commands run from that root.
`;
}

/**
 * Shared marker-splice (b5 discipline): write/refresh a managed block in an
 * AGENTS.md. No file → create it holding only the block; file without the
 * markers → append the block after a blank line; markers present → replace
 * exactly between them. NOTHING outside the markers is ever touched – the
 * rest of the file belongs to the repo.
 */
function spliceBlock(file: string, body: string): void {
	const block = `${AGENTS_BEGIN}\n${body}${AGENTS_END}`;
	if (!existsSync(file)) {
		writeFileSync(file, `${block}\n`);
		return;
	}
	const text = readFileSync(file, "utf8");
	const begin = text.indexOf(AGENTS_BEGIN);
	const end = text.indexOf(AGENTS_END);
	if (begin >= 0 && end > begin) {
		writeFileSync(
			file,
			text.slice(0, begin) + block + text.slice(end + AGENTS_END.length),
		);
		return;
	}
	const base = text.endsWith("\n") ? text : `${text}\n`;
	writeFileSync(file, `${base}\n${block}\n`);
}

/**
 * Write/refresh the standard managed block in the repo root's AGENTS.md (a
 * re-run of `fragmt init` refreshes to the current copy). The body follows
 * the mode the config already records: okfEnabled is read at write time, so
 * no caller threads a parameter – every one of them writes the config FIRST
 * (initRepo/initNestedRepo writeConfig before their call; the CLI's flips
 * run enableOkf before the refresh), which makes a fresh `init --okf`, an
 * existing-repo flip, and a plain re-run all land the right variant between
 * the same v1 fences. okf.ts imports nothing from this module (nor does
 * anything it imports), so the static okfEnabled import closes no cycle.
 */
export function writeAgentsBlock(repoRoot: string): void {
	spliceBlock(
		join(repoRoot, "AGENTS.md"),
		okfEnabled(repoRoot) ? AGENTS_BODY_OKF : AGENTS_BODY,
	);
}

/**
 * Write/refresh the outer repo's redirect block (#16): the nested-init's
 * second call – replaces the standard block the plain init left there.
 */
export function writeOuterAgentsBlock(outerRoot: string, folder: string): void {
	spliceBlock(join(outerRoot, "AGENTS.md"), AGENTS_OUTER_BODY(folder));
}
